// Code generated by mockery v2.34.2. DO NOT EDIT.

package actors

import (
	attack "github.com/kjkondratuk/goblins-and-gold/model/attack"
	item "github.com/kjkondratuk/goblins-and-gold/model/item"

	mock "github.com/stretchr/testify/mock"

	stats "github.com/kjkondratuk/goblins-and-gold/model/stats"
)

// MockPlayer is an autogenerated mock type for the Player type
type MockPlayer struct {
	mock.Mock
}

type MockPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayer) EXPECT() *MockPlayer_Expecter {
	return &MockPlayer_Expecter{mock: &_m.Mock}
}

// AC provides a mock function with given fields:
func (_m *MockPlayer) AC() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPlayer_AC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AC'
type MockPlayer_AC_Call struct {
	*mock.Call
}

// AC is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) AC() *MockPlayer_AC_Call {
	return &MockPlayer_AC_Call{Call: _e.mock.On("AC")}
}

func (_c *MockPlayer_AC_Call) Run(run func()) *MockPlayer_AC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_AC_Call) Return(_a0 int) *MockPlayer_AC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_AC_Call) RunAndReturn(run func() int) *MockPlayer_AC_Call {
	_c.Call.Return(run)
	return _c
}

// Acquire provides a mock function with given fields: _a0
func (_m *MockPlayer) Acquire(_a0 ...item.Item) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockPlayer_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockPlayer_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - _a0 ...item.Item
func (_e *MockPlayer_Expecter) Acquire(_a0 ...interface{}) *MockPlayer_Acquire_Call {
	return &MockPlayer_Acquire_Call{Call: _e.mock.On("Acquire",
		append([]interface{}{}, _a0...)...)}
}

func (_c *MockPlayer_Acquire_Call) Run(run func(_a0 ...item.Item)) *MockPlayer_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]item.Item, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(item.Item)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockPlayer_Acquire_Call) Return() *MockPlayer_Acquire_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_Acquire_Call) RunAndReturn(run func(...item.Item)) *MockPlayer_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Attack provides a mock function with given fields: c, s
func (_m *MockPlayer) Attack(c Combatant, s AttackSelector) bool {
	ret := _m.Called(c, s)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Combatant, AttackSelector) bool); ok {
		r0 = rf(c, s)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPlayer_Attack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attack'
type MockPlayer_Attack_Call struct {
	*mock.Call
}

// Attack is a helper method to define mock.On call
//   - c Combatant
//   - s AttackSelector
func (_e *MockPlayer_Expecter) Attack(c interface{}, s interface{}) *MockPlayer_Attack_Call {
	return &MockPlayer_Attack_Call{Call: _e.mock.On("Attack", c, s)}
}

func (_c *MockPlayer_Attack_Call) Run(run func(c Combatant, s AttackSelector)) *MockPlayer_Attack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Combatant), args[1].(AttackSelector))
	})
	return _c
}

func (_c *MockPlayer_Attack_Call) Return(_a0 bool) *MockPlayer_Attack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Attack_Call) RunAndReturn(run func(Combatant, AttackSelector) bool) *MockPlayer_Attack_Call {
	_c.Call.Return(run)
	return _c
}

// Attacks provides a mock function with given fields:
func (_m *MockPlayer) Attacks() attack.AttackSet {
	ret := _m.Called()

	var r0 attack.AttackSet
	if rf, ok := ret.Get(0).(func() attack.AttackSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(attack.AttackSet)
		}
	}

	return r0
}

// MockPlayer_Attacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attacks'
type MockPlayer_Attacks_Call struct {
	*mock.Call
}

// Attacks is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Attacks() *MockPlayer_Attacks_Call {
	return &MockPlayer_Attacks_Call{Call: _e.mock.On("Attacks")}
}

func (_c *MockPlayer_Attacks_Call) Run(run func()) *MockPlayer_Attacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Attacks_Call) Return(_a0 attack.AttackSet) *MockPlayer_Attacks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Attacks_Call) RunAndReturn(run func() attack.AttackSet) *MockPlayer_Attacks_Call {
	_c.Call.Return(run)
	return _c
}

// BaseStats provides a mock function with given fields:
func (_m *MockPlayer) BaseStats() stats.BaseStats {
	ret := _m.Called()

	var r0 stats.BaseStats
	if rf, ok := ret.Get(0).(func() stats.BaseStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(stats.BaseStats)
	}

	return r0
}

// MockPlayer_BaseStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseStats'
type MockPlayer_BaseStats_Call struct {
	*mock.Call
}

// BaseStats is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) BaseStats() *MockPlayer_BaseStats_Call {
	return &MockPlayer_BaseStats_Call{Call: _e.mock.On("BaseStats")}
}

func (_c *MockPlayer_BaseStats_Call) Run(run func()) *MockPlayer_BaseStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_BaseStats_Call) Return(_a0 stats.BaseStats) *MockPlayer_BaseStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_BaseStats_Call) RunAndReturn(run func() stats.BaseStats) *MockPlayer_BaseStats_Call {
	_c.Call.Return(run)
	return _c
}

// Dmg provides a mock function with given fields: hp
func (_m *MockPlayer) Dmg(hp int) bool {
	ret := _m.Called(hp)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(hp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPlayer_Dmg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dmg'
type MockPlayer_Dmg_Call struct {
	*mock.Call
}

// Dmg is a helper method to define mock.On call
//   - hp int
func (_e *MockPlayer_Expecter) Dmg(hp interface{}) *MockPlayer_Dmg_Call {
	return &MockPlayer_Dmg_Call{Call: _e.mock.On("Dmg", hp)}
}

func (_c *MockPlayer_Dmg_Call) Run(run func(hp int)) *MockPlayer_Dmg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPlayer_Dmg_Call) Return(_a0 bool) *MockPlayer_Dmg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Dmg_Call) RunAndReturn(run func(int) bool) *MockPlayer_Dmg_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields:
func (_m *MockPlayer) Health() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPlayer_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockPlayer_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Health() *MockPlayer_Health_Call {
	return &MockPlayer_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockPlayer_Health_Call) Run(run func()) *MockPlayer_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Health_Call) Return(_a0 int) *MockPlayer_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Health_Call) RunAndReturn(run func() int) *MockPlayer_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Inventory provides a mock function with given fields:
func (_m *MockPlayer) Inventory() []item.Item {
	ret := _m.Called()

	var r0 []item.Item
	if rf, ok := ret.Get(0).(func() []item.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]item.Item)
		}
	}

	return r0
}

// MockPlayer_Inventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inventory'
type MockPlayer_Inventory_Call struct {
	*mock.Call
}

// Inventory is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Inventory() *MockPlayer_Inventory_Call {
	return &MockPlayer_Inventory_Call{Call: _e.mock.On("Inventory")}
}

func (_c *MockPlayer_Inventory_Call) Run(run func()) *MockPlayer_Inventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Inventory_Call) Return(_a0 []item.Item) *MockPlayer_Inventory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Inventory_Call) RunAndReturn(run func() []item.Item) *MockPlayer_Inventory_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockPlayer) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPlayer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPlayer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Name() *MockPlayer_Name_Call {
	return &MockPlayer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPlayer_Name_Call) Run(run func()) *MockPlayer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Name_Call) Return(_a0 string) *MockPlayer_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Name_Call) RunAndReturn(run func() string) *MockPlayer_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Roll provides a mock function with given fields: rollExp
func (_m *MockPlayer) Roll(rollExp string) int {
	ret := _m.Called(rollExp)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(rollExp)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPlayer_Roll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roll'
type MockPlayer_Roll_Call struct {
	*mock.Call
}

// Roll is a helper method to define mock.On call
//   - rollExp string
func (_e *MockPlayer_Expecter) Roll(rollExp interface{}) *MockPlayer_Roll_Call {
	return &MockPlayer_Roll_Call{Call: _e.mock.On("Roll", rollExp)}
}

func (_c *MockPlayer_Roll_Call) Run(run func(rollExp string)) *MockPlayer_Roll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPlayer_Roll_Call) Return(_a0 int) *MockPlayer_Roll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Roll_Call) RunAndReturn(run func(string) int) *MockPlayer_Roll_Call {
	_c.Call.Return(run)
	return _c
}

// Summary provides a mock function with given fields:
func (_m *MockPlayer) Summary() PlayerParams {
	ret := _m.Called()

	var r0 PlayerParams
	if rf, ok := ret.Get(0).(func() PlayerParams); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(PlayerParams)
	}

	return r0
}

// MockPlayer_Summary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summary'
type MockPlayer_Summary_Call struct {
	*mock.Call
}

// Summary is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Summary() *MockPlayer_Summary_Call {
	return &MockPlayer_Summary_Call{Call: _e.mock.On("Summary")}
}

func (_c *MockPlayer_Summary_Call) Run(run func()) *MockPlayer_Summary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Summary_Call) Return(_a0 PlayerParams) *MockPlayer_Summary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Summary_Call) RunAndReturn(run func() PlayerParams) *MockPlayer_Summary_Call {
	_c.Call.Return(run)
	return _c
}

// Unconscious provides a mock function with given fields:
func (_m *MockPlayer) Unconscious() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPlayer_Unconscious_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unconscious'
type MockPlayer_Unconscious_Call struct {
	*mock.Call
}

// Unconscious is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Unconscious() *MockPlayer_Unconscious_Call {
	return &MockPlayer_Unconscious_Call{Call: _e.mock.On("Unconscious")}
}

func (_c *MockPlayer_Unconscious_Call) Run(run func()) *MockPlayer_Unconscious_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Unconscious_Call) Return(_a0 bool) *MockPlayer_Unconscious_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayer_Unconscious_Call) RunAndReturn(run func() bool) *MockPlayer_Unconscious_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayer creates a new instance of MockPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayer {
	mock := &MockPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
