// Code generated by mockery v2.34.2. DO NOT EDIT.

package ux

import mock "github.com/stretchr/testify/mock"

// MockDescribed is an autogenerated mock type for the Described type
type MockDescribed struct {
	mock.Mock
}

type MockDescribed_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDescribed) EXPECT() *MockDescribed_Expecter {
	return &MockDescribed_Expecter{mock: &_m.Mock}
}

// Describe provides a mock function with given fields:
func (_m *MockDescribed) Describe() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDescribed_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type MockDescribed_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
func (_e *MockDescribed_Expecter) Describe() *MockDescribed_Describe_Call {
	return &MockDescribed_Describe_Call{Call: _e.mock.On("Describe")}
}

func (_c *MockDescribed_Describe_Call) Run(run func()) *MockDescribed_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDescribed_Describe_Call) Return(_a0 string) *MockDescribed_Describe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDescribed_Describe_Call) RunAndReturn(run func() string) *MockDescribed_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDescribed creates a new instance of MockDescribed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDescribed(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDescribed {
	mock := &MockDescribed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
