armor:
  - name: "Padded"
    attr: "Dex"
    ac: 11
    stealth: false
    properties:
      - "Light"
  - name: "Leather"
    attr: "Dex"
    ac: 11
    stealth: true
    properties:
      - "Light"
  - name: "Studded Leather"
    attr: "Dex"
    ac: 12
    stealth: true
    properties:
      - "Light"
  - name: "Hide"
    attr: "Dex"
    max: 2
    ac: 12
    stealth: true
    properties:
      - "Medium"
  - name: "Chain Shirt"
    attr: "Dex"
    max: 2
    ac: 13
    stealth: true
    properties:
      - "Medium"
  - name: "Scale Mail"
    attr: "Dex"
    max: 2
    ac: 14
    stealth: false
    properties:
      - "Medium"
  - name: "Breastplate"
    attr: "Dex"
    max: 2
    ac: 14
    stealth: true
    properties:
      - "Medium"
  - name: "Half Plate"
    attr: "Dex"
    max: 2
    ac: 15
    stealth: false
    properties:
      - "Medium"
  - name: "Ring Mail"
    attr: "Str"
    ac: 14
    stealth: false
    properties:
      - "Heavy"
  - name: "Chain Mail"
    attr: "Str"
    min: 13
    ac: 16
    stealth: false
    properties:
      - "Heavy"
  - name: "Splint Mail"
    attr: "Str"
    min: 15
    ac: 17
    stealth: false
    properties:
      - "Heavy"
  - name: "Full Plate"
    attr: "Str"
    min: 15
    ac: 18
    stealth: false
    properties:
      - "Heavy"