// Code generated by mockery v2.34.2. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// mockConfigDataType is an autogenerated mock type for the configDataType type
type mockConfigDataType struct {
	mock.Mock
}

type mockConfigDataType_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigDataType) EXPECT() *mockConfigDataType_Expecter {
	return &mockConfigDataType_Expecter{mock: &_m.Mock}
}

// newMockConfigDataType creates a new instance of mockConfigDataType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigDataType(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigDataType {
	mock := &mockConfigDataType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
